import { useCallback, useEffect, useState } from "react";
import { StyleSheet, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import {
  ActivityIndicator, Button, Card, Chip, Divider, List, ProgressBar, Snackbar, Text, useTheme, Portal,
} from "react-native-paper";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { Screen } from "../../components/Screen";
import { Section } from "../../components/Section";
import { EmptyState } from "../../components/EmptyState";
import { api, errorKey, profileExists, type RecordDto } from "../../lib/api";
import { isLockScreenCardOn } from "../../lib/notifications";
import { formatDate } from "../../lib/format";
import { useSession } from "../../store/session";
import { radius, space } from "../../theme/tokens";

type CheckKey = "name" | "blood" | "allergies" | "contact";
interface Check { key: CheckKey; done: boolean; go: () => void }

const RECENT_LIMIT = 3;
const goProfile = () => router.push("/profile");
// Typed routes are regenerated by Metro once the screen files exist; the object form keeps tsc happy meanwhile.
const goAllergies = () => router.push("/allergies");
const goContacts = () => router.push("/contacts");
const goRecord = (id: string) => router.push(`/record/${id}`);

/** Dashboard: hero card, profile completeness, stat tiles, quick actions and recent documents. */
export default function Home() {
  const { t, i18n } = useTranslation();
  const theme = useTheme();
  const email = useSession((s) => s.email);

  const profile = useQuery({ queryKey: ["profile"], queryFn: api.getProfile });
  const allergies = useQuery({ queryKey: ["allergies"], queryFn: api.listAllergies });
  const contacts = useQuery({ queryKey: ["contacts"], queryFn: api.listContacts });
  const card = useQuery({ queryKey: ["emergency-card"], queryFn: api.emergencyCard });
  const records = useQuery({ queryKey: ["records"], queryFn: api.listRecords });
  const notes = useQuery({ queryKey: ["notifications"], queryFn: api.notifications });

  // Lock-screen pin status lives on the device; re-read whenever the tab regains focus.
  const [lockOn, setLockOn] = useState<boolean | null>(null);
  useFocusEffect(
    useCallback(() => {
      let alive = true;
      isLockScreenCardOn()
        .then((on) => { if (alive) setLockOn(on); })
        .catch(() => { if (alive) setLockOn(false); });
      return () => { alive = false; };
    }, []),
  );

  const hasProfile = profileExists(profile.data);
  // The card endpoint legitimately fails before the first profile save, so only surface it once a profile exists.
  const firstError =
    [profile.error, allergies.error, contacts.error, records.error, notes.error, hasProfile ? card.error : null]
      .find((e) => e != null) ?? null;
  const [msg, setMsg] = useState<string | null>(null);
  useEffect(() => { if (firstError) setMsg(t(errorKey(firstError))); }, [firstError, t]);
  const retryAll = () => {
    void Promise.all([profile.refetch(), allergies.refetch(), contacts.refetch(), card.refetch(), records.refetch(), notes.refetch()]);
  };

  const p = profile.data;
  const blood = p?.bloodAbo;
  const checks: Check[] = [
    { key: "name", done: !!(p?.firstNameTh || p?.nameEn), go: goProfile },
    { key: "blood", done: blood !== undefined && blood !== "unknown", go: goProfile },
    { key: "allergies", done: !!p?.noKnownDrugAllergy || (allergies.data?.length ?? 0) > 0, go: goAllergies },
    { key: "contact", done: (contacts.data?.length ?? 0) > 0, go: goContacts },
  ];
  const doneCount = checks.filter((c) => c.done).length;
  const missing = checks.filter((c) => !c.done);
  const checksLoading = profile.isLoading || allergies.isLoading || contacts.isLoading;

  const unread = (notes.data ?? []).filter((n) => !n.readAt).length;
  const recent = [...(records.data ?? [])].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, RECENT_LIMIT);
  const recordTitle = (r: RecordDto) => r.facility || r.title || t(`records.kinds.${r.kind}`);

  return (
    <>
      <Screen bottomInset={false}>
        <View style={styles.greeting}>
          <Text variant="headlineSmall" style={styles.bold}>{t("home.greeting")}</Text>
          {email ? <Text variant="bodyMedium" style={{ color: theme.colors.onSurfaceVariant }}>{email}</Text> : null}
        </View>

        <View style={[styles.hero, { backgroundColor: theme.colors.primaryContainer }]}>
          <Text variant="titleLarge" style={[styles.bold, { color: theme.colors.onPrimaryContainer }]}>{t("card.title")}</Text>
          {profile.isLoading || (hasProfile && card.isLoading) ? (
            <ActivityIndicator color={theme.colors.onPrimaryContainer} style={styles.heroSpinner} />
          ) : (
            <Text variant="bodyLarge" style={{ color: theme.colors.onPrimaryContainer }}>
              {hasProfile ? t("home.fieldsShared", { count: card.data?.lines.length ?? 0 }) : t("home.setup")}
            </Text>
          )}
          {lockOn !== null ? (
            <Chip
              icon="cellphone-lock"
              compact
              style={[styles.chip, { backgroundColor: theme.colors.surface }]}
              onPress={() => router.push("/lock-screen")}
            >
              {lockOn ? t("home.lockScreenOn") : t("home.lockScreenOff")}
            </Chip>
          ) : null}
          <Button
            mode="contained"
            icon={hasProfile ? "card-account-details-outline" : "account-edit-outline"}
            contentStyle={styles.btnContent}
            labelStyle={styles.btnLabel}
            onPress={() => router.push(hasProfile ? "/card" : "/profile")}
          >
            {hasProfile ? t("home.viewCard") : t("home.editProfile")}
          </Button>
        </View>

        <Section title={t("home.completeness")}>
          <View style={styles.progressWrap}>
            <ProgressBar
              progress={doneCount / checks.length}
              indeterminate={checksLoading}
              color={theme.colors.primary}
              style={styles.progress}
            />
          </View>
          {!checksLoading && missing.length === 0 ? (
            <List.Item
              title={t("home.complete")}
              titleStyle={styles.itemTitle}
              titleNumberOfLines={2}
              left={(props) => <List.Icon {...props} icon="check-circle" color={theme.colors.primary} />}
            />
          ) : (
            missing.map((c, i) => (
              <View key={c.key}>
                {i > 0 ? <Divider /> : null}
                <List.Item
                  title={t(`home.missing.${c.key}`)}
                  titleStyle={styles.itemTitle}
                  titleNumberOfLines={2}
                  onPress={c.go}
                  left={(props) => <List.Icon {...props} icon="checkbox-blank-circle-outline" />}
                  right={(props) => <List.Icon {...props} icon="chevron-right" />}
                />
              </View>
            ))
          )}
        </Section>

        <View style={styles.tiles}>
          <Card mode="contained" style={styles.tile} onPress={() => router.push("/records")}>
            <Card.Content style={styles.tileContent}>
              <Text variant="displaySmall" style={styles.bold}>{records.data ? String(records.data.length) : "—"}</Text>
              <Text variant="bodyLarge">{t("home.records")}</Text>
            </Card.Content>
          </Card>
          <Card mode="contained" style={styles.tile} onPress={() => router.push("/alerts")}>
            <Card.Content style={styles.tileContent}>
              <Text variant="displaySmall" style={styles.bold}>{notes.data ? String(notes.data.length) : "—"}</Text>
              <Text variant="bodyLarge">{t("home.alerts")}</Text>
              {unread > 0 ? (
                <Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant }}>{t("home.unread", { count: unread })}</Text>
              ) : null}
            </Card.Content>
          </Card>
        </View>

        <Section title={t("home.quickActions")} card={false}>
          <View style={styles.actions}>
            <Button mode="contained-tonal" icon="camera-outline" contentStyle={styles.btnContent} labelStyle={styles.btnLabel} onPress={() => router.push("/records")}>
              {t("home.scan")}
            </Button>
            <Button mode="contained-tonal" icon="account-edit-outline" contentStyle={styles.btnContent} labelStyle={styles.btnLabel} onPress={() => router.push("/profile")}>
              {t("home.editProfile")}
            </Button>
            <Button mode="contained-tonal" icon="cellphone-lock" contentStyle={styles.btnContent} labelStyle={styles.btnLabel} onPress={() => router.push("/lock-screen")}>
              {t("lockScreen.title")}
            </Button>
          </View>
        </Section>

        <Section
          title={t("home.recent")}
          action={recent.length > 0 ? <Button compact onPress={() => router.push("/records")}>{t("common.seeAll")}</Button> : undefined}
        >
          {records.isLoading ? (
            <ActivityIndicator style={styles.loading} />
          ) : recent.length === 0 ? (
            <EmptyState icon="file-document-outline" title={t("records.empty")} hint={t("records.emptyHint")} />
          ) : (
            recent.map((r, i) => (
              <View key={r.id}>
                {i > 0 ? <Divider /> : null}
                <List.Item
                  title={recordTitle(r)}
                  description={formatDate(r.issuedAt ?? r.createdAt, i18n.language)}
                  titleStyle={styles.itemTitle}
                  onPress={() => goRecord(r.id)}
                  left={(props) => <List.Icon {...props} icon="file-document-outline" />}
                  right={(props) => <List.Icon {...props} icon="chevron-right" />}
                />
              </View>
            ))
          )}
        </Section>

        <Text variant="bodySmall" style={[styles.disc, { color: theme.colors.onSurfaceVariant }]}>{t("app.disclaimer")}</Text>
      </Screen>

      <Portal><Snackbar
        visible={!!msg}
        onDismiss={() => setMsg(null)}
        duration={4000}
        action={{ label: t("common.retry"), onPress: retryAll }}
      >
        {msg ?? ""}
      </Snackbar></Portal>
    </>
  );
}

const styles = StyleSheet.create({
  greeting: { gap: 2, paddingHorizontal: space.xs },
  bold: { fontWeight: "700" },
  hero: { borderRadius: radius.card, padding: space.lg, gap: space.md },
  heroSpinner: { alignSelf: "flex-start" },
  chip: { alignSelf: "flex-start" },
  btnContent: { minHeight: 48 },
  btnLabel: { fontSize: 16 },
  progressWrap: { paddingHorizontal: space.lg, paddingTop: space.lg, paddingBottom: space.sm },
  progress: { height: 8, borderRadius: radius.pill },
  itemTitle: { fontWeight: "600" },
  tiles: { flexDirection: "row", gap: space.md },
  tile: { flex: 1, borderRadius: radius.lg },
  tileContent: { gap: space.xs, paddingVertical: space.lg },
  actions: { gap: space.sm },
  loading: { marginVertical: space.xl },
  disc: { textAlign: "center", marginTop: space.md },
});
