import { useEffect, useState } from "react";
import { StyleSheet, View } from "react-native";
import { router } from "expo-router";
import Constants from "expo-constants";
import {
  ActivityIndicator, Button, Dialog, Divider, HelperText, List, Portal, SegmentedButtons, Snackbar, Text, TextInput, useTheme,
} from "react-native-paper";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { Screen } from "../../components/Screen";
import { Section } from "../../components/Section";
import { EmptyState } from "../../components/EmptyState";
import { api, errorKey } from "../../lib/api";
import { formatDate, formatDateTime } from "../../lib/format";
import { clearPin, setPin } from "../../lib/pin";
import { setLanguage } from "../../i18n";
import { useSession } from "../../store/session";
import { space } from "../../theme/tokens";

const CONSENT_VERSION = 1;
const MAX_ALERTS = 10;
const PIN_LENGTH = 6;
const PIN_RE = /^\d{6}$/;
const DELETE_WORD = "DELETE";

const digits = (v: string, max: number) => v.replace(/\D/g, "").slice(0, max);
// Typed routes are regenerated by Metro once the screen file exists; the object form keeps tsc happy meanwhile.
const goShare = () => router.push("/share");

/** Settings tab: account, security (PIN), shortcuts, alerts, language, privacy, developer, about. */
export default function More() {
  const { t, i18n } = useTranslation();
  const theme = useTheme();
  const qc = useQueryClient();
  const email = useSession((s) => s.email);
  const pinEnabled = useSession((s) => s.pinEnabled);
  const setPinEnabled = useSession((s) => s.setPinEnabled);
  const apiBaseUrl = useSession((s) => s.apiBaseUrl);
  const setApiBaseUrl = useSession((s) => s.setApiBaseUrl);
  const signOut = useSession((s) => s.signOut);

  const [msg, setMsg] = useState<string | null>(null);
  const [logoutOpen, setLogoutOpen] = useState(false);
  const [logoutBusy, setLogoutBusy] = useState(false);
  const [pinOpen, setPinOpen] = useState(false);
  const [pin1, setPin1] = useState("");
  const [pin2, setPin2] = useState("");
  const [pinError, setPinError] = useState<string | null>(null);
  const [pinBusy, setPinBusy] = useState(false);
  const [withdrawOpen, setWithdrawOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deleteText, setDeleteText] = useState("");
  const [url, setUrl] = useState(apiBaseUrl);
  const [urlBusy, setUrlBusy] = useState(false);

  const notes = useQuery({ queryKey: ["notifications"], queryFn: api.notifications });
  const consent = useQuery({ queryKey: ["consent"], queryFn: api.getConsent });
  const queryError = notes.error ?? consent.error;
  useEffect(() => { if (queryError) setMsg(t(errorKey(queryError))); }, [queryError, t]);

  const sortedNotes = [...(notes.data ?? [])].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const shownNotes = sortedNotes.slice(0, MAX_ALERTS);
  const unreadIds = sortedNotes.filter((n) => !n.readAt).map((n) => n.id);

  const markRead = useMutation({
    mutationFn: async (ids: string[]) => { for (const id of ids) await api.markNotificationRead(id); },
    onError: (e) => setMsg(t(errorKey(e))),
    onSettled: () => void qc.invalidateQueries({ queryKey: ["notifications"] }),
  });

  const withdraw = useMutation({
    mutationFn: () => api.postConsent(consent.data?.version ?? CONSENT_VERSION, {}, false),
    onSuccess: () => {
      setMsg(t("privacy.withdrawn"));
      void qc.invalidateQueries({ queryKey: ["consent"] });
      void qc.invalidateQueries({ queryKey: ["share-links"] });
    },
    onError: (e) => setMsg(t(errorKey(e))),
    onSettled: () => setWithdrawOpen(false),
  });

  const deleteAccount = useMutation({
    mutationFn: () => api.deleteAccount(),
    onSuccess: async () => {
      setDeleteOpen(false);
      await signOut();
      qc.clear();
    },
    onError: (e) => setMsg(t(errorKey(e))),
  });

  function openPinDialog() {
    setPin1("");
    setPin2("");
    setPinError(null);
    setPinOpen(true);
  }

  async function savePin() {
    if (!PIN_RE.test(pin1)) { setPinError(t("security.pinLength")); return; }
    if (pin1 !== pin2) { setPinError(t("security.pinMismatch")); return; }
    setPinBusy(true);
    try {
      await setPin(pin1);
      setPinEnabled(true);
      setPinOpen(false);
      setMsg(t("security.pinSaved"));
    } catch (e) {
      setPinError(t(errorKey(e)));
    } finally {
      setPinBusy(false);
    }
  }

  async function removePin() {
    try {
      await clearPin();
      setPinEnabled(false);
      setMsg(t("security.pinRemoved"));
    } catch (e) {
      setMsg(t(errorKey(e)));
    }
  }

  async function logout() {
    setLogoutBusy(true);
    try { await api.logout(); } catch { /* best effort: the server session may already be gone */ }
    await signOut(); // the root guard redirects to /login
    qc.clear(); // never show one account's cached data to the next
  }

  async function saveUrl() {
    const next = url.trim();
    if (!next) return;
    setUrlBusy(true);
    try {
      await setApiBaseUrl(next);
      setUrl(next);
      setMsg(t("more.serverUrlSaved"));
      void qc.invalidateQueries();
    } catch (e) {
      setMsg(t(errorKey(e)));
    } finally {
      setUrlBusy(false);
    }
  }

  const version = Constants.expoConfig?.version ?? "1.0.0";
  const lang = i18n.language === "en" ? "en" : "th";
  const consentStatus = consent.data?.granted
    ? t("privacy.consentGiven", { date: formatDate(consent.data.at, i18n.language) })
    : t("privacy.noConsent");
  const canDelete = deleteText.trim() === DELETE_WORD;
  const urlDirty = url.trim().length > 0 && url.trim() !== apiBaseUrl;
  const dim = { color: theme.colors.onSurfaceVariant };

  return (
    <>
      <Screen bottomInset={false}>
        <Section title={t("more.account")}>
          <List.Item
            title={email ?? t("common.unknown")}
            description={t("more.signedInAs")}
            titleStyle={styles.itemTitle}
            left={(props) => <List.Icon {...props} icon="account-circle" />}
          />
          <View style={styles.pad}>
            <Button mode="contained-tonal" icon="logout" contentStyle={styles.btnContent} onPress={() => setLogoutOpen(true)}>
              {t("auth.logout")}
            </Button>
          </View>
        </Section>

        <Section title={t("more.security")}>
          <List.Item
            title={t("security.pin")}
            titleStyle={styles.itemTitle}
            description={`${pinEnabled ? t("security.pinSet") : t("security.pinNotSet")} · ${t("security.pinHint")}`}
            descriptionNumberOfLines={3}
            left={(props) => <List.Icon {...props} icon={pinEnabled ? "lock" : "lock-open-variant-outline"} />}
          />
          <View style={[styles.pad, styles.row]}>
            <Button mode="contained-tonal" icon="form-textbox-password" contentStyle={styles.btnContent} style={styles.grow} onPress={openPinDialog}>
              {pinEnabled ? t("security.changePin") : t("security.setPin")}
            </Button>
            {pinEnabled ? (
              <Button mode="outlined" icon="lock-remove" contentStyle={styles.btnContent} style={styles.grow} onPress={() => void removePin()}>
                {t("security.removePin")}
              </Button>
            ) : null}
          </View>
        </Section>

        <Section>
          <List.Item
            title={t("more.emergencyProfile")}
            titleStyle={styles.itemTitle}
            onPress={() => router.push("/profile")}
            left={(props) => <List.Icon {...props} icon="account-heart-outline" />}
            right={(props) => <List.Icon {...props} icon="chevron-right" />}
          />
          <Divider />
          <List.Item
            title={t("more.lockScreen")}
            titleStyle={styles.itemTitle}
            onPress={() => router.push("/lock-screen")}
            left={(props) => <List.Icon {...props} icon="cellphone-lock" />}
            right={(props) => <List.Icon {...props} icon="chevron-right" />}
          />
          <Divider />
          <List.Item
            title={t("more.shareClinician")}
            titleStyle={styles.itemTitle}
            onPress={goShare}
            left={(props) => <List.Icon {...props} icon="share-variant-outline" />}
            right={(props) => <List.Icon {...props} icon="chevron-right" />}
          />
        </Section>

        <Section
          title={t("alerts.title")}
          action={unreadIds.length > 0 ? (
            <Button compact onPress={() => markRead.mutate(unreadIds)} loading={markRead.isPending} disabled={markRead.isPending}>
              {t("alerts.markAllRead")}
            </Button>
          ) : undefined}
        >
          {notes.isLoading ? (
            <ActivityIndicator style={styles.loading} />
          ) : shownNotes.length === 0 ? (
            <EmptyState icon="bell-outline" title={t("alerts.empty")} hint={t("alerts.emptyHint")} />
          ) : (
            shownNotes.map((n, i) => {
              const unread = !n.readAt;
              return (
                <View key={n.id}>
                  {i > 0 ? <Divider /> : null}
                  <List.Item
                    title={t(`alerts.kinds.${n.kind}`, { defaultValue: n.kind })}
                    titleNumberOfLines={3}
                    titleStyle={unread ? styles.itemTitle : undefined}
                    description={formatDateTime(n.createdAt, i18n.language)}
                    onPress={unread ? () => markRead.mutate([n.id]) : undefined}
                    left={(props) => (
                      <List.Icon
                        {...props}
                        icon={unread ? "bell-badge" : "bell-outline"}
                        color={unread ? theme.colors.primary : theme.colors.onSurfaceVariant}
                      />
                    )}
                  />
                </View>
              );
            })
          )}
        </Section>

        <Section title={t("more.language")}>
          <View style={styles.pad}>
            <SegmentedButtons
              value={lang}
              onValueChange={(v) => void setLanguage(v === "en" ? "en" : "th")}
              buttons={[
                { value: "th", label: t("more.thai") },
                { value: "en", label: t("more.english") },
              ]}
            />
          </View>
        </Section>

        <Section title={t("more.privacy")}>
          <View style={styles.pad}>
            <Text variant="bodySmall" style={dim}>{t("privacy.dataProtection")}</Text>
            <Divider style={styles.divider} />
            {consent.isLoading ? (
              <ActivityIndicator style={styles.loadingSmall} />
            ) : (
              <Text variant="bodyLarge" style={styles.itemTitle}>{consentStatus}</Text>
            )}
            <Text variant="bodySmall" style={dim}>{t("privacy.withdrawHint")}</Text>
            <Button mode="outlined" icon="shield-off-outline" contentStyle={styles.btnContent} onPress={() => setWithdrawOpen(true)}>
              {t("privacy.withdraw")}
            </Button>
            <Divider style={styles.divider} />
            <Text variant="bodySmall" style={dim}>{t("privacy.deleteHint")}</Text>
            <Button
              mode="text"
              icon="delete-forever-outline"
              textColor={theme.colors.error}
              contentStyle={styles.btnContent}
              onPress={() => { setDeleteText(""); setDeleteOpen(true); }}
            >
              {t("privacy.deleteAccount")}
            </Button>
          </View>
        </Section>

        <Section title={t("more.developer")}>
          <View style={styles.pad}>
            <TextInput
              mode="outlined"
              label={t("more.serverUrl")}
              value={url}
              onChangeText={setUrl}
              autoCapitalize="none"
              autoCorrect={false}
              keyboardType="url"
            />
            <HelperText type="info" visible>{t("more.serverUrlHint")}</HelperText>
            <Button
              mode="contained-tonal"
              icon="content-save-outline"
              contentStyle={styles.btnContent}
              onPress={() => void saveUrl()}
              loading={urlBusy}
              disabled={urlBusy || !urlDirty}
            >
              {t("common.save")}
            </Button>
          </View>
        </Section>

        <Section title={t("more.about")}>
          <List.Item
            title={t("app.name")}
            titleStyle={styles.itemTitle}
            description={t("more.version", { version })}
            left={(props) => <List.Icon {...props} icon="information-outline" />}
          />
          <View style={styles.pad}>
            <Text variant="bodySmall" style={dim}>{t("app.disclaimer")}</Text>
          </View>
        </Section>
      </Screen>

      <Portal>
        <Dialog visible={logoutOpen} onDismiss={() => { if (!logoutBusy) setLogoutOpen(false); }}>
          <Dialog.Title>{t("auth.logout")}</Dialog.Title>
          <Dialog.Content>
            <Text variant="bodyLarge">{t("auth.logoutConfirm")}</Text>
          </Dialog.Content>
          <Dialog.Actions>
            <Button onPress={() => setLogoutOpen(false)} disabled={logoutBusy}>{t("common.cancel")}</Button>
            <Button mode="contained" onPress={() => void logout()} loading={logoutBusy} disabled={logoutBusy}>{t("auth.logout")}</Button>
          </Dialog.Actions>
        </Dialog>

        <Dialog visible={pinOpen} onDismiss={() => { if (!pinBusy) setPinOpen(false); }}>
          <Dialog.Title>{pinEnabled ? t("security.changePin") : t("security.setPin")}</Dialog.Title>
          <Dialog.Content style={styles.form}>
            <TextInput
              mode="outlined"
              label={t("security.newPin")}
              value={pin1}
              onChangeText={(v) => { setPin1(digits(v, PIN_LENGTH)); setPinError(null); }}
              keyboardType="number-pad"
              secureTextEntry
              maxLength={PIN_LENGTH}
              autoFocus
            />
            <TextInput
              mode="outlined"
              label={t("security.confirmPin")}
              value={pin2}
              onChangeText={(v) => { setPin2(digits(v, PIN_LENGTH)); setPinError(null); }}
              keyboardType="number-pad"
              secureTextEntry
              maxLength={PIN_LENGTH}
              error={!!pinError}
            />
            <HelperText type={pinError ? "error" : "info"} visible>{pinError ?? t("security.pinHint")}</HelperText>
          </Dialog.Content>
          <Dialog.Actions>
            <Button onPress={() => setPinOpen(false)} disabled={pinBusy}>{t("common.cancel")}</Button>
            <Button mode="contained" onPress={() => void savePin()} loading={pinBusy} disabled={pinBusy}>{t("common.save")}</Button>
          </Dialog.Actions>
        </Dialog>

        <Dialog visible={withdrawOpen} onDismiss={() => { if (!withdraw.isPending) setWithdrawOpen(false); }}>
          <Dialog.Title>{t("privacy.withdraw")}</Dialog.Title>
          <Dialog.Content>
            <Text variant="bodyLarge">{t("privacy.withdrawConfirm")}</Text>
          </Dialog.Content>
          <Dialog.Actions>
            <Button onPress={() => setWithdrawOpen(false)} disabled={withdraw.isPending}>{t("common.cancel")}</Button>
            <Button mode="contained" onPress={() => withdraw.mutate()} loading={withdraw.isPending} disabled={withdraw.isPending}>
              {t("common.confirm")}
            </Button>
          </Dialog.Actions>
        </Dialog>

        <Dialog visible={deleteOpen} onDismiss={() => { if (!deleteAccount.isPending) setDeleteOpen(false); }}>
          <Dialog.Title>{t("privacy.deleteAccount")}</Dialog.Title>
          <Dialog.Content style={styles.form}>
            <Text variant="bodyLarge">{t("privacy.deleteConfirm")}</Text>
            <TextInput
              mode="outlined"
              label={t("privacy.typeDelete")}
              value={deleteText}
              onChangeText={setDeleteText}
              autoCapitalize="characters"
              autoCorrect={false}
            />
          </Dialog.Content>
          <Dialog.Actions>
            <Button onPress={() => setDeleteOpen(false)} disabled={deleteAccount.isPending}>{t("common.cancel")}</Button>
            <Button
              mode="contained"
              buttonColor={theme.colors.error}
              textColor={theme.colors.onError}
              onPress={() => deleteAccount.mutate()}
              loading={deleteAccount.isPending}
              disabled={!canDelete || deleteAccount.isPending}
            >
              {t("common.delete")}
            </Button>
          </Dialog.Actions>
        </Dialog>
      </Portal>

      <Portal><Snackbar visible={!!msg} onDismiss={() => setMsg(null)} duration={3000}>{msg ?? ""}</Snackbar></Portal>
    </>
  );
}

const styles = StyleSheet.create({
  pad: { padding: space.lg, gap: space.md },
  row: { flexDirection: "row", flexWrap: "wrap" },
  grow: { flexGrow: 1, flexBasis: 140 },
  itemTitle: { fontWeight: "600" },
  btnContent: { minHeight: 48 },
  divider: { marginVertical: space.xs },
  loading: { marginVertical: space.xl },
  loadingSmall: { alignSelf: "flex-start" },
  form: { gap: space.sm },
});
